package testutil

import "strings"

// RegisteredDetectorFixtures returns one deliberately non-functional positive
// fixture for every compile-time detector. The catalog is shared by the
// registry-wide matcher test and detector-to-verifier contract test so neither
// layer can prove compatibility with hand-built RawFinding values that a real
// detector never emits.
func RegisteredDetectorFixtures() map[string][]byte {
	repeat := strings.Repeat
	return map[string][]byte{
		"airtable-pat":               []byte("AIRTABLE_TOKEN=patAb12Cd34Ef56Gh." + repeat("ab12cd34", 8)),
		"anthropic-api-key":          []byte("ANTHROPIC_API_KEY=sk-ant-" + repeat("Ab12Cd34_", 10)),
		"auth0-management-token":     []byte("AUTH0_MANAGEMENT_TOKEN=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2ZpeHR1cmUuZXUuYXV0aDAuY29tLyJ9.c2lnbmF0dXJlLWZpeHR1cmU"),
		"aws-access-key-id":          []byte("aws_access_key_id=AKIAQ7M2PL9RT4VW8XYZ\naws_secret_access_key=" + repeat("Ab1/", 10)),
		"azure-entra-secret":         []byte("AZURE_CLIENT_SECRET=" + repeat("Ab12Cd34", 5)),
		"azure-storage-key":          []byte("DefaultEndpointsProtocol=https;AccountName=syntheticacct;AccountKey=" + repeat("Ab12Cd34", 11) + ";"),
		"bitbucket-app-password":     []byte("BITBUCKET_USERNAME=fixture-user\nBITBUCKET_APP_PASSWORD=" + repeat("Ab12", 5)),
		"circleci-token":             []byte("CIRCLECI_TOKEN=CCIPAT_" + repeat("Ab12Cd34_", 6)),
		"cloudflare-api-token":       []byte("CLOUDFLARE_API_TOKEN=" + repeat("Ab12Cd34", 5)),
		"coinbase-api-key":           []byte("COINBASE_API_KEY=" + repeat("Ab12Cd34", 4)),
		"database-connection-string": []byte("postgres://fixture_user:synthetic_password@db.example.invalid:5432/app"),
		"databricks-token":           []byte("DATABRICKS_HOST=https://fixture.cloud.databricks.com\nDATABRICKS_TOKEN=dapi" + repeat("ab12cd34", 4)),
		"datadog-api-key":            []byte("DATADOG_API_KEY=" + repeat("ab12cd34", 4)),
		"deepseek-api-key":           []byte("DEEPSEEK_API_KEY=sk-" + repeat("ab12cd34", 4)),
		"digitalocean-token":         []byte("DIGITALOCEAN_TOKEN=dop_v1_" + repeat("ab12cd34", 8)),
		"discord-bot-token":          []byte("DISCORD_TOKEN=M" + repeat("Ab1c", 5) + "Xyz.Ab1Cd2." + repeat("Abc1", 6) + "XyZ"),
		"discord-webhook-url":        []byte("https://discord.com/api/webhooks/123456789012345678/" + repeat("Ab12Cd34_", 4)),
		"dockerhub-pat":              []byte("DOCKER_TOKEN=dckr_pat_" + repeat("Ab12Cd34_", 4)),
		"doppler-token":              []byte("DOPPLER_TOKEN=dp.st." + repeat("Ab12Cd34_", 5)),
		"figma-pat":                  []byte("FIGMA_TOKEN=figd_" + repeat("Ab12Cd34_", 5)),
		"ftp-credentials":            []byte("ftp://fixture-user:synthetic-password@ftp.example.invalid:21/uploads"),
		"gcp-service-account":        []byte(`{"type":"service_account","project_id":"fixture-project","private_key_id":"abcdef1234567890abcdef1234567890abcdef12","client_email":"fixture@fixture-project.iam.gserviceaccount.com"}`),
		"generic-api-key":            []byte(`api_key = "Q7mN2pL9rT4vW8xYzC6bH3kF"`),
		"github-oauth-token":         []byte("GITHUB_TOKEN=gho_" + repeat("Ab12Cd34_", 4)),
		"github-token":               []byte("GITHUB_TOKEN=ghp_" + repeat("Ab12Cd34_", 4)),
		"gitlab-pat":                 []byte("GITLAB_TOKEN=glpat-" + repeat("Ab12Cd34_", 3)),
		"grafana-api-key":            []byte("GRAFANA_TOKEN=glsa_" + repeat("Ab12Cd34", 4) + "_abcdef12"),
		"hashicorp-vault-token":      []byte("VAULT_TOKEN=hvs." + repeat("Ab12Cd34_", 3)),
		"heroku-api-key":             []byte("HEROKU_API_KEY=12345678-1234-abcd-9876-1234567890ab"),
		"huggingface-token":          []byte("HF_TOKEN=hf_" + repeat("Ab12Cd34", 5)),
		"infura-api-key":             []byte("INFURA_API_KEY=" + repeat("ab12cd34", 4)),
		"jwt":                        []byte("Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0NTY3ODkwIn0." + repeat("Ab12Cd34", 4)),
		"launchdarkly-sdk-key":       []byte("LAUNCHDARKLY_SDK_KEY=sdk-abcdef01-2345-6789-abcd-0123456789ab"),
		"ldap-credentials":           []byte("ldaps://fixture-user:synthetic-password@ldap.example.invalid:636/dc=example,dc=invalid"),
		"linear-api-key":             []byte("LINEAR_API_KEY=lin_api_" + repeat("Ab12Cd34", 5)),
		"mailgun-api-key":            []byte("MAILGUN_API_KEY=key-" + repeat("ab12cd34", 4)),
		"newrelic-api-key":           []byte("NEW_RELIC_API_KEY=NRAK-" + repeat("AB12CD34X", 3)),
		"notion-token":               []byte("NOTION_TOKEN=ntn_" + repeat("Ab12Cd34", 6)),
		"npm-token":                  []byte("NPM_TOKEN=npm_" + repeat("Ab12Cd34X", 4)),
		"okta-api-token":             []byte("OKTA_ORG=https://fixture.okta.com\nAuthorization: SSWS 00" + repeat("Ab12Cd34", 5)),
		"openai-api-key":             []byte("OPENAI_API_KEY=sk-proj-" + repeat("Ab12Cd34_", 6)),
		"pagerduty-api-key":          []byte("PAGERDUTY_API_KEY=u+" + repeat("Ab12Cd34_", 3)),
		"postmark-server-token":      []byte("POSTMARK_SERVER_TOKEN=abcdef01-2345-6789-abcd-0123456789ab"),
		"private-key":                []byte("-----BEGIN PRIVATE KEY-----\nSYNTHETIC-NOT-KEY-MATERIAL\n-----END PRIVATE KEY-----"),
		"pypi-api-token":             []byte("PYPI_TOKEN=pypi-AgEIcHlwaS5vcmc" + repeat("Ab12Cd34_", 7)),
		"rabbitmq-connection-string": []byte("amqps://fixture-user:synthetic-password@rabbitmq.example.invalid:5671/vhost"),
		"redis-connection-string":    []byte("rediss://fixture-user:synthetic-password@cache.example.invalid:6380/0"),
		"rubygems-api-key":           []byte("RUBYGEMS_API_KEY=rubygems_" + repeat("ab12cd34", 6)),
		"sendgrid-api-key":           []byte("SENDGRID_API_KEY=SG." + repeat("Ab12Cd34_Xy", 2) + "." + repeat("Ab12Cd34_", 5)),
		"sentry-token":               []byte("SENTRY_AUTH_TOKEN=sntrys_" + repeat("Ab12Cd34_", 5)),
		"shopify-access-token":       []byte("SHOPIFY_ACCESS_TOKEN=shpat_" + repeat("ab12cd34", 4)),
		"slack-token":                []byte("SLACK_TOKEN=xoxb-123456789012-123456789012-" + repeat("Ab12Cd34", 3)),
		"slack-webhook":              []byte("https://hooks.slack.com/services/TABCDEF12/BABCDEF12/" + repeat("Ab12Cd34", 3)),
		"snowflake-credentials":      []byte("account.snowflakecomputing.com/?warehouse=fixture&password=synthetic-password"),
		"snyk-api-key":               []byte("SNYK_TOKEN=abcdef01-2345-6789-abcd-0123456789ab"),
		"sonarcloud-token":           []byte("SONAR_TOKEN=sqp_" + repeat("ab12cd34", 5)),
		"stripe-api-key-live":        []byte("STRIPE_SECRET_KEY=sk_live_" + repeat("Ab12Cd34", 3)),
		"stripe-api-key-test":        []byte("STRIPE_TEST_KEY=sk_test_" + repeat("Ab12Cd34", 3)),
		"structured-config-secret":   []byte(`{"Database":{"Password":"Q7mN2pL9rT4vW8xYzC6bH3kF"}}`),
		"supabase-service-key":       []byte("SUPABASE_ACCESS_TOKEN=sbp_" + repeat("ab12cd34", 5)),
		"teams-webhook":              []byte("https://fixture.webhook.office.com/webhookb2/abcdef01-2345-6789-abcd-ef0123456789/IncomingWebhook/abcdef0123456789/abcdef01-2345-6789-abcd-ef0123456789"),
		"telegram-bot-token":         []byte("TELEGRAM_BOT_TOKEN=123456789:" + repeat("Ab12Cd3", 5)),
		"terraform-cloud-token":      []byte("TERRAFORM_TOKEN=" + repeat("Ab12Cd3", 2) + ".atlasv1." + repeat("Ab12Cd34", 9)),
		"twilio-api-key":             []byte("TWILIO_API_KEY_SID=SK" + repeat("ab12cd34", 4) + "\nTWILIO_API_KEY_SECRET=synthetic-opaque-value-Ab12Cd34"),
		"vercel-token":               []byte("VERCEL_TOKEN=vercel_" + repeat("Ab12Cd34_", 3)),
	}
}
